name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare SDK Tools and Accept Licenses
      run: |
        # 1. Prepara pasta do SDK
        SDK_DIR="/github/home/.buildozer/android/platform/android-sdk"
        mkdir -p "$SDK_DIR/cmdline-tools"
        mkdir -p "$SDK_DIR/licenses"

        # 2. Injeta as licencas aprovadas
        echo -e "\n89330422945ba52063944006f23e64d4730637b0\nd56f5187479451eabf01fb78af6d623501d07141\n7a93463f031e200753a373977531398c8e146c65\n84831b9409646aed3fee35e3022141983513410f\n7863a34a17950c0c707525381a1796d420786524\n504667f4c0571343f11d137b079095f9c490a072\ne6b7c2ee7d02636a04a37f5f403932e6047c699f" > "$SDK_DIR/licenses/android-sdk-license"

        # 3. Baixa as ferramentas de linha de comando usando wget
        wget -q -O cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9441241_latest.zip
        unzip -q cmdline-tools.zip -d "$SDK_DIR/cmdline-tools"
        mv "$SDK_DIR/cmdline-tools/cmdline-tools" "$SDK_DIR/cmdline-tools/latest"
        rm cmdline-tools.zip

        # 4. Cria o link simbolico para o caminho antigo que o Buildozer procura
        mkdir -p "$SDK_DIR/tools"
        ln -s "$SDK_DIR/cmdline-tools/latest/bin" "$SDK_DIR/tools/bin"

    - name: Build APK
      env:
        BUILDOZER_WARN_ON_ROOT: "0"
      run: |
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: teste_som
        path: bin/*.apk
